//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aluno", Namespace="http://schemas.datacontract.org/2004/07/ufmt.services.entities")]
    [System.SerializableAttribute()]
    public partial class Aluno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CampusUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ChaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoBancoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoCursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CursoUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaeAlunoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeAlunoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeBancoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeCampusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroContaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaiAlunoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RgaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SemestreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SituacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneSecundarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoGraduacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TurnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string anoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.TipoEstudante tipoEstudanteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Agencia {
            get {
                return this.AgenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.AgenciaField, value) != true)) {
                    this.AgenciaField = value;
                    this.RaisePropertyChanged("Agencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CEP {
            get {
                return this.CEPField;
            }
            set {
                if ((object.ReferenceEquals(this.CEPField, value) != true)) {
                    this.CEPField = value;
                    this.RaisePropertyChanged("CEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CampusUID {
            get {
                return this.CampusUIDField;
            }
            set {
                if ((this.CampusUIDField.Equals(value) != true)) {
                    this.CampusUIDField = value;
                    this.RaisePropertyChanged("CampusUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Chave {
            get {
                return this.ChaveField;
            }
            set {
                if ((this.ChaveField.Equals(value) != true)) {
                    this.ChaveField = value;
                    this.RaisePropertyChanged("Chave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoBanco {
            get {
                return this.CodigoBancoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoBancoField, value) != true)) {
                    this.CodigoBancoField = value;
                    this.RaisePropertyChanged("CodigoBanco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCurso {
            get {
                return this.CodigoCursoField;
            }
            set {
                if ((this.CodigoCursoField.Equals(value) != true)) {
                    this.CodigoCursoField = value;
                    this.RaisePropertyChanged("CodigoCurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cpf {
            get {
                return this.CpfField;
            }
            set {
                if ((object.ReferenceEquals(this.CpfField, value) != true)) {
                    this.CpfField = value;
                    this.RaisePropertyChanged("Cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Curso {
            get {
                return this.CursoField;
            }
            set {
                if ((object.ReferenceEquals(this.CursoField, value) != true)) {
                    this.CursoField = value;
                    this.RaisePropertyChanged("Curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CursoUID {
            get {
                return this.CursoUIDField;
            }
            set {
                if ((this.CursoUIDField.Equals(value) != true)) {
                    this.CursoUIDField = value;
                    this.RaisePropertyChanged("CursoUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaeAluno {
            get {
                return this.MaeAlunoField;
            }
            set {
                if ((object.ReferenceEquals(this.MaeAlunoField, value) != true)) {
                    this.MaeAlunoField = value;
                    this.RaisePropertyChanged("MaeAluno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((this.MatriculaField.Equals(value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeAluno {
            get {
                return this.NomeAlunoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeAlunoField, value) != true)) {
                    this.NomeAlunoField = value;
                    this.RaisePropertyChanged("NomeAluno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeBanco {
            get {
                return this.NomeBancoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeBancoField, value) != true)) {
                    this.NomeBancoField = value;
                    this.RaisePropertyChanged("NomeBanco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeCampus {
            get {
                return this.NomeCampusField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeCampusField, value) != true)) {
                    this.NomeCampusField = value;
                    this.RaisePropertyChanged("NomeCampus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroConta {
            get {
                return this.NumeroContaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroContaField, value) != true)) {
                    this.NumeroContaField = value;
                    this.RaisePropertyChanged("NumeroConta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaiAluno {
            get {
                return this.PaiAlunoField;
            }
            set {
                if ((object.ReferenceEquals(this.PaiAlunoField, value) != true)) {
                    this.PaiAlunoField = value;
                    this.RaisePropertyChanged("PaiAluno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Regime {
            get {
                return this.RegimeField;
            }
            set {
                if ((object.ReferenceEquals(this.RegimeField, value) != true)) {
                    this.RegimeField = value;
                    this.RaisePropertyChanged("Regime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rg {
            get {
                return this.RgField;
            }
            set {
                if ((object.ReferenceEquals(this.RgField, value) != true)) {
                    this.RgField = value;
                    this.RaisePropertyChanged("Rg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rga {
            get {
                return this.RgaField;
            }
            set {
                if ((object.ReferenceEquals(this.RgaField, value) != true)) {
                    this.RgaField = value;
                    this.RaisePropertyChanged("Rga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Semestre {
            get {
                return this.SemestreField;
            }
            set {
                if ((object.ReferenceEquals(this.SemestreField, value) != true)) {
                    this.SemestreField = value;
                    this.RaisePropertyChanged("Semestre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Situacao {
            get {
                return this.SituacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.SituacaoField, value) != true)) {
                    this.SituacaoField = value;
                    this.RaisePropertyChanged("Situacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone {
            get {
                return this.TelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true)) {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefoneSecundario {
            get {
                return this.TelefoneSecundarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneSecundarioField, value) != true)) {
                    this.TelefoneSecundarioField = value;
                    this.RaisePropertyChanged("TelefoneSecundario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoGraduacao {
            get {
                return this.TipoGraduacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoGraduacaoField, value) != true)) {
                    this.TipoGraduacaoField = value;
                    this.RaisePropertyChanged("TipoGraduacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Turno {
            get {
                return this.TurnoField;
            }
            set {
                if ((object.ReferenceEquals(this.TurnoField, value) != true)) {
                    this.TurnoField = value;
                    this.RaisePropertyChanged("Turno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UF {
            get {
                return this.UFField;
            }
            set {
                if ((object.ReferenceEquals(this.UFField, value) != true)) {
                    this.UFField = value;
                    this.RaisePropertyChanged("UF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ano {
            get {
                return this.anoField;
            }
            set {
                if ((object.ReferenceEquals(this.anoField, value) != true)) {
                    this.anoField = value;
                    this.RaisePropertyChanged("ano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.TipoEstudante tipoEstudante {
            get {
                return this.tipoEstudanteField;
            }
            set {
                if ((this.tipoEstudanteField.Equals(value) != true)) {
                    this.tipoEstudanteField = value;
                    this.RaisePropertyChanged("tipoEstudante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoEstudante", Namespace="http://schemas.datacontract.org/2004/07/ufmt.services")]
    public enum TipoEstudante : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Graduacao = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PosGraduacao = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParametrosEstudante", Namespace="http://schemas.datacontract.org/2004/07/ufmt.services")]
    public enum ParametrosEstudante : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        rga = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        cpf = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        rg = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        nome = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaltasPorEstudante", Namespace="http://schemas.datacontract.org/2004/07/ufmt.services")]
    [System.SerializableAttribute()]
    public partial class FaltasPorEstudante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int faltasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double notaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rgaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int faltas {
            get {
                return this.faltasField;
            }
            set {
                if ((this.faltasField.Equals(value) != true)) {
                    this.faltasField = value;
                    this.RaisePropertyChanged("faltas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nota {
            get {
                return this.notaField;
            }
            set {
                if ((this.notaField.Equals(value) != true)) {
                    this.notaField = value;
                    this.RaisePropertyChanged("nota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rga {
            get {
                return this.rgaField;
            }
            set {
                if ((object.ReferenceEquals(this.rgaField, value) != true)) {
                    this.rgaField = value;
                    this.RaisePropertyChanged("rga");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoFaltasEstudante", Namespace="http://schemas.datacontract.org/2004/07/ufmt.services")]
    [System.SerializableAttribute()]
    public partial class ResultadoFaltasEstudante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int resultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rgaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int resultado {
            get {
                return this.resultadoField;
            }
            set {
                if ((this.resultadoField.Equals(value) != true)) {
                    this.resultadoField = value;
                    this.RaisePropertyChanged("resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rga {
            get {
                return this.rgaField;
            }
            set {
                if ((object.ReferenceEquals(this.rgaField, value) != true)) {
                    this.rgaField = value;
                    this.RaisePropertyChanged("rga");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlunoSigaReference.IAlunoSiga")]
    public interface IAlunoSiga {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetInfoAluno", ReplyAction="http://tempuri.org/IAlunoSiga/GetInfoAlunoResponse")]
        ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno GetInfoAluno(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetInfoAluno", ReplyAction="http://tempuri.org/IAlunoSiga/GetInfoAlunoResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno> GetInfoAlunoAsync(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetInfoAlunoInativo", ReplyAction="http://tempuri.org/IAlunoSiga/GetInfoAlunoInativoResponse")]
        ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno GetInfoAlunoInativo(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetInfoAlunoInativo", ReplyAction="http://tempuri.org/IAlunoSiga/GetInfoAlunoInativoResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno> GetInfoAlunoInativoAsync(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunos", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosResponse")]
        ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunos", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> GetAlunosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunosPorCpf", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosPorCpfResponse")]
        ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosPorCpf(string cpf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunosPorCpf", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosPorCpfResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> GetAlunosPorCpfAsync(string cpf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunosInativosPorCpf", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosInativosPorCpfResponse")]
        ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosInativosPorCpf(string cpf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunosInativosPorCpf", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosInativosPorCpfResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> GetAlunosInativosPorCpfAsync(string cpf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunosPorCampus", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosPorCampusResponse")]
        ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosPorCampus(int campusUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunosPorCampus", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosPorCampusResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> GetAlunosPorCampusAsync(int campusUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunosGraduacao", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosGraduacaoResponse")]
        ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosGraduacao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunosGraduacao", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosGraduacaoResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> GetAlunosGraduacaoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunosGraduacaoPorCampus", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosGraduacaoPorCampusResponse")]
        ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosGraduacaoPorCampus(int campusUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunosGraduacaoPorCampus", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosGraduacaoPorCampusResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> GetAlunosGraduacaoPorCampusAsync(int campusUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunosPaginado", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosPaginadoResponse")]
        ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosPaginado(int registroInicial, int quantidadeRegistros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunosPaginado", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosPaginadoResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> GetAlunosPaginadoAsync(int registroInicial, int quantidadeRegistros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunosPorCampusPaginado", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosPorCampusPaginadoResponse")]
        ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosPorCampusPaginado(int campusUID, int registroInicial, int quantidadeRegistros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunosPorCampusPaginado", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosPorCampusPaginadoResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> GetAlunosPorCampusPaginadoAsync(int campusUID, int registroInicial, int quantidadeRegistros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetCoeficiente", ReplyAction="http://tempuri.org/IAlunoSiga/GetCoeficienteResponse")]
        double GetCoeficiente(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetCoeficiente", ReplyAction="http://tempuri.org/IAlunoSiga/GetCoeficienteResponse")]
        System.Threading.Tasks.Task<double> GetCoeficienteAsync(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunosPorNome", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosPorNomeResponse")]
        ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.GetAlunosPorNomeResponse GetAlunosPorNome(ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.GetAlunosPorNomeRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunosPorNome", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosPorNomeResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.GetAlunosPorNomeResponse> GetAlunosPorNomeAsync(ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.GetAlunosPorNomeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunosInativosPorNome", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosInativosPorNomeResponse")]
        ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosInativosPorNome(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetAlunosInativosPorNome", ReplyAction="http://tempuri.org/IAlunoSiga/GetAlunosInativosPorNomeResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> GetAlunosInativosPorNomeAsync(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/ConsultaGenerica", ReplyAction="http://tempuri.org/IAlunoSiga/ConsultaGenericaResponse")]
        ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] ConsultaGenerica(ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.ParametrosEstudante nomeParametro, string valorParametro, int registroInicial, int quantidadeDeRegistros, System.Nullable<int> campusUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/ConsultaGenerica", ReplyAction="http://tempuri.org/IAlunoSiga/ConsultaGenericaResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> ConsultaGenericaAsync(ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.ParametrosEstudante nomeParametro, string valorParametro, int registroInicial, int quantidadeDeRegistros, System.Nullable<int> campusUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GravaFaltasEstudanteGraduacao", ReplyAction="http://tempuri.org/IAlunoSiga/GravaFaltasEstudanteGraduacaoResponse")]
        int GravaFaltasEstudanteGraduacao(string usuario, string IP, string rga, string disciplina, int periodo, string turma, int faltas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GravaFaltasEstudanteGraduacao", ReplyAction="http://tempuri.org/IAlunoSiga/GravaFaltasEstudanteGraduacaoResponse")]
        System.Threading.Tasks.Task<int> GravaFaltasEstudanteGraduacaoAsync(string usuario, string IP, string rga, string disciplina, int periodo, string turma, int faltas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GravaFaltasEstudantesGraduacao", ReplyAction="http://tempuri.org/IAlunoSiga/GravaFaltasEstudantesGraduacaoResponse")]
        ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.ResultadoFaltasEstudante[] GravaFaltasEstudantesGraduacao(string usuario, string IP, string disciplina, int periodo, string turma, ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.FaltasPorEstudante[] faltasPorEstudante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GravaFaltasEstudantesGraduacao", ReplyAction="http://tempuri.org/IAlunoSiga/GravaFaltasEstudantesGraduacaoResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.ResultadoFaltasEstudante[]> GravaFaltasEstudantesGraduacaoAsync(string usuario, string IP, string disciplina, int periodo, string turma, ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.FaltasPorEstudante[] faltasPorEstudante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/DesligaAlunoSiga", ReplyAction="http://tempuri.org/IAlunoSiga/DesligaAlunoSigaResponse")]
        void DesligaAlunoSiga(string rga, string usuario, string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/DesligaAlunoSiga", ReplyAction="http://tempuri.org/IAlunoSiga/DesligaAlunoSigaResponse")]
        System.Threading.Tasks.Task DesligaAlunoSigaAsync(string rga, string usuario, string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/IncluiDisciplinaHistorico", ReplyAction="http://tempuri.org/IAlunoSiga/IncluiDisciplinaHistoricoResponse")]
        bool IncluiDisciplinaHistorico(string usuario, string ip, string rga, int disciplina, int periodo, string turma, string protocolo, string condDisci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/IncluiDisciplinaHistorico", ReplyAction="http://tempuri.org/IAlunoSiga/IncluiDisciplinaHistoricoResponse")]
        System.Threading.Tasks.Task<bool> IncluiDisciplinaHistoricoAsync(string usuario, string ip, string rga, int disciplina, int periodo, string turma, string protocolo, string condDisci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/RemoverDisciplinaHistorico", ReplyAction="http://tempuri.org/IAlunoSiga/RemoverDisciplinaHistoricoResponse")]
        bool RemoverDisciplinaHistorico(string usuario, string ip, string rga, int disciplina, int periodo, string turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/RemoverDisciplinaHistorico", ReplyAction="http://tempuri.org/IAlunoSiga/RemoverDisciplinaHistoricoResponse")]
        System.Threading.Tasks.Task<bool> RemoverDisciplinaHistoricoAsync(string usuario, string ip, string rga, int disciplina, int periodo, string turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/VerificaPendenciasBiblioteca", ReplyAction="http://tempuri.org/IAlunoSiga/VerificaPendenciasBibliotecaResponse")]
        bool VerificaPendenciasBiblioteca(string parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/VerificaPendenciasBiblioteca", ReplyAction="http://tempuri.org/IAlunoSiga/VerificaPendenciasBibliotecaResponse")]
        System.Threading.Tasks.Task<bool> VerificaPendenciasBibliotecaAsync(string parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/AlterarSenhaAluno", ReplyAction="http://tempuri.org/IAlunoSiga/AlterarSenhaAlunoResponse")]
        void AlterarSenhaAluno(string rga, string senha_antiga, string nova_senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/AlterarSenhaAluno", ReplyAction="http://tempuri.org/IAlunoSiga/AlterarSenhaAlunoResponse")]
        System.Threading.Tasks.Task AlterarSenhaAlunoAsync(string rga, string senha_antiga, string nova_senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/AlterarDadosCadastrais", ReplyAction="http://tempuri.org/IAlunoSiga/AlterarDadosCadastraisResponse")]
        bool AlterarDadosCadastrais(string rga, string TelefonePrimario, string telefoneSecundario, string Mail, string linkLattes, byte[] image, string content_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/AlterarDadosCadastrais", ReplyAction="http://tempuri.org/IAlunoSiga/AlterarDadosCadastraisResponse")]
        System.Threading.Tasks.Task<bool> AlterarDadosCadastraisAsync(string rga, string TelefonePrimario, string telefoneSecundario, string Mail, string linkLattes, byte[] image, string content_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/ReenvioSenhaAluno", ReplyAction="http://tempuri.org/IAlunoSiga/ReenvioSenhaAlunoResponse")]
        bool ReenvioSenhaAluno(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/ReenvioSenhaAluno", ReplyAction="http://tempuri.org/IAlunoSiga/ReenvioSenhaAlunoResponse")]
        System.Threading.Tasks.Task<bool> ReenvioSenhaAlunoAsync(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/VerificarCargaHorariaCursada", ReplyAction="http://tempuri.org/IAlunoSiga/VerificarCargaHorariaCursadaResponse")]
        string VerificarCargaHorariaCursada(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/VerificarCargaHorariaCursada", ReplyAction="http://tempuri.org/IAlunoSiga/VerificarCargaHorariaCursadaResponse")]
        System.Threading.Tasks.Task<string> VerificarCargaHorariaCursadaAsync(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/VerificaBolsaAluno", ReplyAction="http://tempuri.org/IAlunoSiga/VerificaBolsaAlunoResponse")]
        bool VerificaBolsaAluno(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/VerificaBolsaAluno", ReplyAction="http://tempuri.org/IAlunoSiga/VerificaBolsaAlunoResponse")]
        System.Threading.Tasks.Task<bool> VerificaBolsaAlunoAsync(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/VerificaReprovacoesSemestresAnteriores", ReplyAction="http://tempuri.org/IAlunoSiga/VerificaReprovacoesSemestresAnterioresResponse")]
        int VerificaReprovacoesSemestresAnteriores(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/VerificaReprovacoesSemestresAnteriores", ReplyAction="http://tempuri.org/IAlunoSiga/VerificaReprovacoesSemestresAnterioresResponse")]
        System.Threading.Tasks.Task<int> VerificaReprovacoesSemestresAnterioresAsync(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetCoeficientePorMediaAritmetica", ReplyAction="http://tempuri.org/IAlunoSiga/GetCoeficientePorMediaAritmeticaResponse")]
        float GetCoeficientePorMediaAritmetica(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetCoeficientePorMediaAritmetica", ReplyAction="http://tempuri.org/IAlunoSiga/GetCoeficientePorMediaAritmeticaResponse")]
        System.Threading.Tasks.Task<float> GetCoeficientePorMediaAritmeticaAsync(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/VerificaAprovacoesSemestresIniciais", ReplyAction="http://tempuri.org/IAlunoSiga/VerificaAprovacoesSemestresIniciaisResponse")]
        bool VerificaAprovacoesSemestresIniciais(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/VerificaAprovacoesSemestresIniciais", ReplyAction="http://tempuri.org/IAlunoSiga/VerificaAprovacoesSemestresIniciaisResponse")]
        System.Threading.Tasks.Task<bool> VerificaAprovacoesSemestresIniciaisAsync(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetInfoAlunoAndifes", ReplyAction="http://tempuri.org/IAlunoSiga/GetInfoAlunoAndifesResponse")]
        ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno GetInfoAlunoAndifes(string rga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoSiga/GetInfoAlunoAndifes", ReplyAction="http://tempuri.org/IAlunoSiga/GetInfoAlunoAndifesResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno> GetInfoAlunoAndifesAsync(string rga);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAlunosPorNome", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAlunosPorNomeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nome;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int registroInicial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int quantidadeDeRegistros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Nullable<int> campusUID;
        
        public GetAlunosPorNomeRequest() {
        }
        
        public GetAlunosPorNomeRequest(string nome, int registroInicial, int quantidadeDeRegistros, System.Nullable<int> campusUID) {
            this.nome = nome;
            this.registroInicial = registroInicial;
            this.quantidadeDeRegistros = quantidadeDeRegistros;
            this.campusUID = campusUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAlunosPorNomeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAlunosPorNomeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosPorNomeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int quantidadeTotal;
        
        public GetAlunosPorNomeResponse() {
        }
        
        public GetAlunosPorNomeResponse(ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosPorNomeResult, int quantidadeTotal) {
            this.GetAlunosPorNomeResult = GetAlunosPorNomeResult;
            this.quantidadeTotal = quantidadeTotal;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlunoSigaChannel : ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.IAlunoSiga, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlunoSigaClient : System.ServiceModel.ClientBase<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.IAlunoSiga>, ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.IAlunoSiga {
        
        public AlunoSigaClient() {
        }
        
        public AlunoSigaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlunoSigaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlunoSigaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlunoSigaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno GetInfoAluno(string rga) {
            return base.Channel.GetInfoAluno(rga);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno> GetInfoAlunoAsync(string rga) {
            return base.Channel.GetInfoAlunoAsync(rga);
        }
        
        public ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno GetInfoAlunoInativo(string rga) {
            return base.Channel.GetInfoAlunoInativo(rga);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno> GetInfoAlunoInativoAsync(string rga) {
            return base.Channel.GetInfoAlunoInativoAsync(rga);
        }
        
        public ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunos() {
            return base.Channel.GetAlunos();
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> GetAlunosAsync() {
            return base.Channel.GetAlunosAsync();
        }
        
        public ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosPorCpf(string cpf) {
            return base.Channel.GetAlunosPorCpf(cpf);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> GetAlunosPorCpfAsync(string cpf) {
            return base.Channel.GetAlunosPorCpfAsync(cpf);
        }
        
        public ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosInativosPorCpf(string cpf) {
            return base.Channel.GetAlunosInativosPorCpf(cpf);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> GetAlunosInativosPorCpfAsync(string cpf) {
            return base.Channel.GetAlunosInativosPorCpfAsync(cpf);
        }
        
        public ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosPorCampus(int campusUID) {
            return base.Channel.GetAlunosPorCampus(campusUID);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> GetAlunosPorCampusAsync(int campusUID) {
            return base.Channel.GetAlunosPorCampusAsync(campusUID);
        }
        
        public ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosGraduacao() {
            return base.Channel.GetAlunosGraduacao();
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> GetAlunosGraduacaoAsync() {
            return base.Channel.GetAlunosGraduacaoAsync();
        }
        
        public ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosGraduacaoPorCampus(int campusUID) {
            return base.Channel.GetAlunosGraduacaoPorCampus(campusUID);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> GetAlunosGraduacaoPorCampusAsync(int campusUID) {
            return base.Channel.GetAlunosGraduacaoPorCampusAsync(campusUID);
        }
        
        public ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosPaginado(int registroInicial, int quantidadeRegistros) {
            return base.Channel.GetAlunosPaginado(registroInicial, quantidadeRegistros);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> GetAlunosPaginadoAsync(int registroInicial, int quantidadeRegistros) {
            return base.Channel.GetAlunosPaginadoAsync(registroInicial, quantidadeRegistros);
        }
        
        public ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosPorCampusPaginado(int campusUID, int registroInicial, int quantidadeRegistros) {
            return base.Channel.GetAlunosPorCampusPaginado(campusUID, registroInicial, quantidadeRegistros);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> GetAlunosPorCampusPaginadoAsync(int campusUID, int registroInicial, int quantidadeRegistros) {
            return base.Channel.GetAlunosPorCampusPaginadoAsync(campusUID, registroInicial, quantidadeRegistros);
        }
        
        public double GetCoeficiente(string rga) {
            return base.Channel.GetCoeficiente(rga);
        }
        
        public System.Threading.Tasks.Task<double> GetCoeficienteAsync(string rga) {
            return base.Channel.GetCoeficienteAsync(rga);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.GetAlunosPorNomeResponse ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.IAlunoSiga.GetAlunosPorNome(ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.GetAlunosPorNomeRequest request) {
            return base.Channel.GetAlunosPorNome(request);
        }
        
        public ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosPorNome(string nome, int registroInicial, int quantidadeDeRegistros, System.Nullable<int> campusUID, out int quantidadeTotal) {
            ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.GetAlunosPorNomeRequest inValue = new ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.GetAlunosPorNomeRequest();
            inValue.nome = nome;
            inValue.registroInicial = registroInicial;
            inValue.quantidadeDeRegistros = quantidadeDeRegistros;
            inValue.campusUID = campusUID;
            ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.GetAlunosPorNomeResponse retVal = ((ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.IAlunoSiga)(this)).GetAlunosPorNome(inValue);
            quantidadeTotal = retVal.quantidadeTotal;
            return retVal.GetAlunosPorNomeResult;
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.GetAlunosPorNomeResponse> GetAlunosPorNomeAsync(ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.GetAlunosPorNomeRequest request) {
            return base.Channel.GetAlunosPorNomeAsync(request);
        }
        
        public ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] GetAlunosInativosPorNome(string nome) {
            return base.Channel.GetAlunosInativosPorNome(nome);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> GetAlunosInativosPorNomeAsync(string nome) {
            return base.Channel.GetAlunosInativosPorNomeAsync(nome);
        }
        
        public ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[] ConsultaGenerica(ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.ParametrosEstudante nomeParametro, string valorParametro, int registroInicial, int quantidadeDeRegistros, System.Nullable<int> campusUID) {
            return base.Channel.ConsultaGenerica(nomeParametro, valorParametro, registroInicial, quantidadeDeRegistros, campusUID);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno[]> ConsultaGenericaAsync(ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.ParametrosEstudante nomeParametro, string valorParametro, int registroInicial, int quantidadeDeRegistros, System.Nullable<int> campusUID) {
            return base.Channel.ConsultaGenericaAsync(nomeParametro, valorParametro, registroInicial, quantidadeDeRegistros, campusUID);
        }
        
        public int GravaFaltasEstudanteGraduacao(string usuario, string IP, string rga, string disciplina, int periodo, string turma, int faltas) {
            return base.Channel.GravaFaltasEstudanteGraduacao(usuario, IP, rga, disciplina, periodo, turma, faltas);
        }
        
        public System.Threading.Tasks.Task<int> GravaFaltasEstudanteGraduacaoAsync(string usuario, string IP, string rga, string disciplina, int periodo, string turma, int faltas) {
            return base.Channel.GravaFaltasEstudanteGraduacaoAsync(usuario, IP, rga, disciplina, periodo, turma, faltas);
        }
        
        public ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.ResultadoFaltasEstudante[] GravaFaltasEstudantesGraduacao(string usuario, string IP, string disciplina, int periodo, string turma, ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.FaltasPorEstudante[] faltasPorEstudante) {
            return base.Channel.GravaFaltasEstudantesGraduacao(usuario, IP, disciplina, periodo, turma, faltasPorEstudante);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.ResultadoFaltasEstudante[]> GravaFaltasEstudantesGraduacaoAsync(string usuario, string IP, string disciplina, int periodo, string turma, ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.FaltasPorEstudante[] faltasPorEstudante) {
            return base.Channel.GravaFaltasEstudantesGraduacaoAsync(usuario, IP, disciplina, periodo, turma, faltasPorEstudante);
        }
        
        public void DesligaAlunoSiga(string rga, string usuario, string ip) {
            base.Channel.DesligaAlunoSiga(rga, usuario, ip);
        }
        
        public System.Threading.Tasks.Task DesligaAlunoSigaAsync(string rga, string usuario, string ip) {
            return base.Channel.DesligaAlunoSigaAsync(rga, usuario, ip);
        }
        
        public bool IncluiDisciplinaHistorico(string usuario, string ip, string rga, int disciplina, int periodo, string turma, string protocolo, string condDisci) {
            return base.Channel.IncluiDisciplinaHistorico(usuario, ip, rga, disciplina, periodo, turma, protocolo, condDisci);
        }
        
        public System.Threading.Tasks.Task<bool> IncluiDisciplinaHistoricoAsync(string usuario, string ip, string rga, int disciplina, int periodo, string turma, string protocolo, string condDisci) {
            return base.Channel.IncluiDisciplinaHistoricoAsync(usuario, ip, rga, disciplina, periodo, turma, protocolo, condDisci);
        }
        
        public bool RemoverDisciplinaHistorico(string usuario, string ip, string rga, int disciplina, int periodo, string turma) {
            return base.Channel.RemoverDisciplinaHistorico(usuario, ip, rga, disciplina, periodo, turma);
        }
        
        public System.Threading.Tasks.Task<bool> RemoverDisciplinaHistoricoAsync(string usuario, string ip, string rga, int disciplina, int periodo, string turma) {
            return base.Channel.RemoverDisciplinaHistoricoAsync(usuario, ip, rga, disciplina, periodo, turma);
        }
        
        public bool VerificaPendenciasBiblioteca(string parametro) {
            return base.Channel.VerificaPendenciasBiblioteca(parametro);
        }
        
        public System.Threading.Tasks.Task<bool> VerificaPendenciasBibliotecaAsync(string parametro) {
            return base.Channel.VerificaPendenciasBibliotecaAsync(parametro);
        }
        
        public void AlterarSenhaAluno(string rga, string senha_antiga, string nova_senha) {
            base.Channel.AlterarSenhaAluno(rga, senha_antiga, nova_senha);
        }
        
        public System.Threading.Tasks.Task AlterarSenhaAlunoAsync(string rga, string senha_antiga, string nova_senha) {
            return base.Channel.AlterarSenhaAlunoAsync(rga, senha_antiga, nova_senha);
        }
        
        public bool AlterarDadosCadastrais(string rga, string TelefonePrimario, string telefoneSecundario, string Mail, string linkLattes, byte[] image, string content_type) {
            return base.Channel.AlterarDadosCadastrais(rga, TelefonePrimario, telefoneSecundario, Mail, linkLattes, image, content_type);
        }
        
        public System.Threading.Tasks.Task<bool> AlterarDadosCadastraisAsync(string rga, string TelefonePrimario, string telefoneSecundario, string Mail, string linkLattes, byte[] image, string content_type) {
            return base.Channel.AlterarDadosCadastraisAsync(rga, TelefonePrimario, telefoneSecundario, Mail, linkLattes, image, content_type);
        }
        
        public bool ReenvioSenhaAluno(string rga) {
            return base.Channel.ReenvioSenhaAluno(rga);
        }
        
        public System.Threading.Tasks.Task<bool> ReenvioSenhaAlunoAsync(string rga) {
            return base.Channel.ReenvioSenhaAlunoAsync(rga);
        }
        
        public string VerificarCargaHorariaCursada(string rga) {
            return base.Channel.VerificarCargaHorariaCursada(rga);
        }
        
        public System.Threading.Tasks.Task<string> VerificarCargaHorariaCursadaAsync(string rga) {
            return base.Channel.VerificarCargaHorariaCursadaAsync(rga);
        }
        
        public bool VerificaBolsaAluno(string rga) {
            return base.Channel.VerificaBolsaAluno(rga);
        }
        
        public System.Threading.Tasks.Task<bool> VerificaBolsaAlunoAsync(string rga) {
            return base.Channel.VerificaBolsaAlunoAsync(rga);
        }
        
        public int VerificaReprovacoesSemestresAnteriores(string rga) {
            return base.Channel.VerificaReprovacoesSemestresAnteriores(rga);
        }
        
        public System.Threading.Tasks.Task<int> VerificaReprovacoesSemestresAnterioresAsync(string rga) {
            return base.Channel.VerificaReprovacoesSemestresAnterioresAsync(rga);
        }
        
        public float GetCoeficientePorMediaAritmetica(string rga) {
            return base.Channel.GetCoeficientePorMediaAritmetica(rga);
        }
        
        public System.Threading.Tasks.Task<float> GetCoeficientePorMediaAritmeticaAsync(string rga) {
            return base.Channel.GetCoeficientePorMediaAritmeticaAsync(rga);
        }
        
        public bool VerificaAprovacoesSemestresIniciais(string rga) {
            return base.Channel.VerificaAprovacoesSemestresIniciais(rga);
        }
        
        public System.Threading.Tasks.Task<bool> VerificaAprovacoesSemestresIniciaisAsync(string rga) {
            return base.Channel.VerificaAprovacoesSemestresIniciaisAsync(rga);
        }
        
        public ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno GetInfoAlunoAndifes(string rga) {
            return base.Channel.GetInfoAlunoAndifes(rga);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.AlunoSigaReference.Aluno> GetInfoAlunoAndifesAsync(string rga) {
            return base.Channel.GetInfoAlunoAndifesAsync(rga);
        }
    }
}
