//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ufmt.br.bolsa.auxilio.siafi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroCredor
    {
        public int IdCadastroCredor { get; set; }
        public string Remessa { get; set; }
        public string CodigoUG { get; set; }
        public string CPFServidorResponsavel { get; set; }
        public string DataGeracao { get; set; }
        public string HoraGeracao { get; set; }
        public string CPFBolsista { get; set; }
        public string NomeBolsista { get; set; }
        public string EnderecoBolsista { get; set; }
        public string CodigoMunicipioSIAFI { get; set; }
        public string CodigoPaisSIAFI { get; set; }
        public string TelefoneBolsista { get; set; }
        public string FAXBolsista { get; set; }
        public string CEPUFMT { get; set; }
        public string CodigoBancoBolsista { get; set; }
        public string AgenciaBancoBolsista { get; set; }
        public string ContaCorrenteBolsista { get; set; }
        public string TipoContaSIAFI { get; set; }
        public string UGSupridoraSIAFI { get; set; }
        public string GestaoSupridoraSIAFI { get; set; }
    }
}
