//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ufmt.br.bolsa.auxilio.siafi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaCredor
    {
        public long IdListaCredor { get; set; }
        public string RGA { get; set; }
        public string CPF { get; set; }
        public string Banco { get; set; }
        public string Agencia { get; set; }
        public string Conta { get; set; }
        public string Valor { get; set; }
        public string NumeroLC { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<int> NumeroRemessaLC { get; set; }
    }
}
