//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ufmt.br.bolsa.auxilio.siafi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaCredorSiafi
    {
        public long IdListaCredor { get; set; }
        public string HeaderListaCredor { get; set; }
        public string DetalheListaCredor { get; set; }
        public string TraillerListaCredor { get; set; }
        public System.DateTime MesAnoReferencia { get; set; }
        public string NumeroLista { get; set; }
    }
}
