//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ufmt.br.bolsa.auxilio.siafi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbbolsaspraeEntities : DbContext
    {
        public dbbolsaspraeEntities()
            : base("name=dbbolsaspraeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CadastroCredor> CadastroCredor { get; set; }
        public virtual DbSet<CadastroCredorSiafi> CadastroCredorSiafi { get; set; }
        public virtual DbSet<ListaCredor> ListaCredor { get; set; }
        public virtual DbSet<ListaCredorSiafi> ListaCredorSiafi { get; set; }
    }
}
