//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnidadeEntity", Namespace="http://schemas.datacontract.org/2004/07/ufmt.services.entities")]
    [System.SerializableAttribute()]
    public partial class UnidadeEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char AtivaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CampusUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HierarquiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiglaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoUnidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UnidadeSuperiorUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UnidadeUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Ativa {
            get {
                return this.AtivaField;
            }
            set {
                if ((this.AtivaField.Equals(value) != true)) {
                    this.AtivaField = value;
                    this.RaisePropertyChanged("Ativa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campus {
            get {
                return this.CampusField;
            }
            set {
                if ((object.ReferenceEquals(this.CampusField, value) != true)) {
                    this.CampusField = value;
                    this.RaisePropertyChanged("Campus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CampusUID {
            get {
                return this.CampusUIDField;
            }
            set {
                if ((this.CampusUIDField.Equals(value) != true)) {
                    this.CampusUIDField = value;
                    this.RaisePropertyChanged("CampusUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hierarquia {
            get {
                return this.HierarquiaField;
            }
            set {
                if ((object.ReferenceEquals(this.HierarquiaField, value) != true)) {
                    this.HierarquiaField = value;
                    this.RaisePropertyChanged("Hierarquia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sigla {
            get {
                return this.SiglaField;
            }
            set {
                if ((object.ReferenceEquals(this.SiglaField, value) != true)) {
                    this.SiglaField = value;
                    this.RaisePropertyChanged("Sigla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoUnidade {
            get {
                return this.TipoUnidadeField;
            }
            set {
                if ((this.TipoUnidadeField.Equals(value) != true)) {
                    this.TipoUnidadeField = value;
                    this.RaisePropertyChanged("TipoUnidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UnidadeSuperiorUID {
            get {
                return this.UnidadeSuperiorUIDField;
            }
            set {
                if ((this.UnidadeSuperiorUIDField.Equals(value) != true)) {
                    this.UnidadeSuperiorUIDField = value;
                    this.RaisePropertyChanged("UnidadeSuperiorUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UnidadeUID {
            get {
                return this.UnidadeUIDField;
            }
            set {
                if ((this.UnidadeUIDField.Equals(value) != true)) {
                    this.UnidadeUIDField = value;
                    this.RaisePropertyChanged("UnidadeUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CampusEntity", Namespace="http://schemas.datacontract.org/2004/07/ufmt.services.entities")]
    [System.SerializableAttribute()]
    public partial class CampusEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CampusUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CampusUID {
            get {
                return this.CampusUIDField;
            }
            set {
                if ((this.CampusUIDField.Equals(value) != true)) {
                    this.CampusUIDField = value;
                    this.RaisePropertyChanged("CampusUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CampiEntity", Namespace="http://schemas.datacontract.org/2004/07/ufmt.services.entities")]
    [System.SerializableAttribute()]
    public partial class CampiEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int campusUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoExternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int campusUID {
            get {
                return this.campusUIDField;
            }
            set {
                if ((this.campusUIDField.Equals(value) != true)) {
                    this.campusUIDField = value;
                    this.RaisePropertyChanged("campusUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigoExterno {
            get {
                return this.codigoExternoField;
            }
            set {
                if ((this.codigoExternoField.Equals(value) != true)) {
                    this.codigoExternoField = value;
                    this.RaisePropertyChanged("codigoExterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pessoa", Namespace="http://schemas.datacontract.org/2004/07/ufmt.sig.entity")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.PessoaEntity))]
    public partial class Pessoa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cpfField;
        
        private string ctpsField;
        
        private string ctpsSerieField;
        
        private string ctpsUfField;
        
        private string enderecoBairroField;
        
        private string enderecoCepField;
        
        private string enderecoComplementoField;
        
        private string enderecoLogradouroField;
        
        private string enderecoMunicipioField;
        
        private string enderecoNumeroField;
        
        private string enderecoUfField;
        
        private string mailField;
        
        private System.DateTime nascimentoDataField;
        
        private string nomeField;
        
        private string nomeMaeField;
        
        private string nomePaiField;
        
        private long pessoaUIDField;
        
        private string pisPasepField;
        
        private string rgField;
        
        private System.Nullable<System.DateTime> rgDataExpedicaoField;
        
        private string rgOrgaoExpedidorField;
        
        private string rgUfField;
        
        private char sexoField;
        
        private string telefoneComercialField;
        
        private string telefonePrimarioField;
        
        private string telefoneSecundarioField;
        
        private ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.TipoTitulacao tipoTitulacaoField;
        
        private string tituloEleitorField;
        
        private System.Nullable<System.DateTime> tituloEleitorDataEmissaoField;
        
        private string tituloEleitorSecaoField;
        
        private string tituloEleitorUfField;
        
        private string tituloEleitorZonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                if ((object.ReferenceEquals(this.cpfField, value) != true)) {
                    this.cpfField = value;
                    this.RaisePropertyChanged("cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ctps {
            get {
                return this.ctpsField;
            }
            set {
                if ((object.ReferenceEquals(this.ctpsField, value) != true)) {
                    this.ctpsField = value;
                    this.RaisePropertyChanged("ctps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ctpsSerie {
            get {
                return this.ctpsSerieField;
            }
            set {
                if ((object.ReferenceEquals(this.ctpsSerieField, value) != true)) {
                    this.ctpsSerieField = value;
                    this.RaisePropertyChanged("ctpsSerie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ctpsUf {
            get {
                return this.ctpsUfField;
            }
            set {
                if ((object.ReferenceEquals(this.ctpsUfField, value) != true)) {
                    this.ctpsUfField = value;
                    this.RaisePropertyChanged("ctpsUf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string enderecoBairro {
            get {
                return this.enderecoBairroField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoBairroField, value) != true)) {
                    this.enderecoBairroField = value;
                    this.RaisePropertyChanged("enderecoBairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string enderecoCep {
            get {
                return this.enderecoCepField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoCepField, value) != true)) {
                    this.enderecoCepField = value;
                    this.RaisePropertyChanged("enderecoCep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string enderecoComplemento {
            get {
                return this.enderecoComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoComplementoField, value) != true)) {
                    this.enderecoComplementoField = value;
                    this.RaisePropertyChanged("enderecoComplemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string enderecoLogradouro {
            get {
                return this.enderecoLogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoLogradouroField, value) != true)) {
                    this.enderecoLogradouroField = value;
                    this.RaisePropertyChanged("enderecoLogradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string enderecoMunicipio {
            get {
                return this.enderecoMunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoMunicipioField, value) != true)) {
                    this.enderecoMunicipioField = value;
                    this.RaisePropertyChanged("enderecoMunicipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string enderecoNumero {
            get {
                return this.enderecoNumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoNumeroField, value) != true)) {
                    this.enderecoNumeroField = value;
                    this.RaisePropertyChanged("enderecoNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string enderecoUf {
            get {
                return this.enderecoUfField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoUfField, value) != true)) {
                    this.enderecoUfField = value;
                    this.RaisePropertyChanged("enderecoUf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime nascimentoData {
            get {
                return this.nascimentoDataField;
            }
            set {
                if ((this.nascimentoDataField.Equals(value) != true)) {
                    this.nascimentoDataField = value;
                    this.RaisePropertyChanged("nascimentoData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nomeMae {
            get {
                return this.nomeMaeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeMaeField, value) != true)) {
                    this.nomeMaeField = value;
                    this.RaisePropertyChanged("nomeMae");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nomePai {
            get {
                return this.nomePaiField;
            }
            set {
                if ((object.ReferenceEquals(this.nomePaiField, value) != true)) {
                    this.nomePaiField = value;
                    this.RaisePropertyChanged("nomePai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long pessoaUID {
            get {
                return this.pessoaUIDField;
            }
            set {
                if ((this.pessoaUIDField.Equals(value) != true)) {
                    this.pessoaUIDField = value;
                    this.RaisePropertyChanged("pessoaUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string pisPasep {
            get {
                return this.pisPasepField;
            }
            set {
                if ((object.ReferenceEquals(this.pisPasepField, value) != true)) {
                    this.pisPasepField = value;
                    this.RaisePropertyChanged("pisPasep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string rg {
            get {
                return this.rgField;
            }
            set {
                if ((object.ReferenceEquals(this.rgField, value) != true)) {
                    this.rgField = value;
                    this.RaisePropertyChanged("rg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> rgDataExpedicao {
            get {
                return this.rgDataExpedicaoField;
            }
            set {
                if ((this.rgDataExpedicaoField.Equals(value) != true)) {
                    this.rgDataExpedicaoField = value;
                    this.RaisePropertyChanged("rgDataExpedicao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string rgOrgaoExpedidor {
            get {
                return this.rgOrgaoExpedidorField;
            }
            set {
                if ((object.ReferenceEquals(this.rgOrgaoExpedidorField, value) != true)) {
                    this.rgOrgaoExpedidorField = value;
                    this.RaisePropertyChanged("rgOrgaoExpedidor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string rgUf {
            get {
                return this.rgUfField;
            }
            set {
                if ((object.ReferenceEquals(this.rgUfField, value) != true)) {
                    this.rgUfField = value;
                    this.RaisePropertyChanged("rgUf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public char sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((this.sexoField.Equals(value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string telefoneComercial {
            get {
                return this.telefoneComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.telefoneComercialField, value) != true)) {
                    this.telefoneComercialField = value;
                    this.RaisePropertyChanged("telefoneComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string telefonePrimario {
            get {
                return this.telefonePrimarioField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonePrimarioField, value) != true)) {
                    this.telefonePrimarioField = value;
                    this.RaisePropertyChanged("telefonePrimario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string telefoneSecundario {
            get {
                return this.telefoneSecundarioField;
            }
            set {
                if ((object.ReferenceEquals(this.telefoneSecundarioField, value) != true)) {
                    this.telefoneSecundarioField = value;
                    this.RaisePropertyChanged("telefoneSecundario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.TipoTitulacao tipoTitulacao {
            get {
                return this.tipoTitulacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoTitulacaoField, value) != true)) {
                    this.tipoTitulacaoField = value;
                    this.RaisePropertyChanged("tipoTitulacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tituloEleitor {
            get {
                return this.tituloEleitorField;
            }
            set {
                if ((object.ReferenceEquals(this.tituloEleitorField, value) != true)) {
                    this.tituloEleitorField = value;
                    this.RaisePropertyChanged("tituloEleitor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> tituloEleitorDataEmissao {
            get {
                return this.tituloEleitorDataEmissaoField;
            }
            set {
                if ((this.tituloEleitorDataEmissaoField.Equals(value) != true)) {
                    this.tituloEleitorDataEmissaoField = value;
                    this.RaisePropertyChanged("tituloEleitorDataEmissao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tituloEleitorSecao {
            get {
                return this.tituloEleitorSecaoField;
            }
            set {
                if ((object.ReferenceEquals(this.tituloEleitorSecaoField, value) != true)) {
                    this.tituloEleitorSecaoField = value;
                    this.RaisePropertyChanged("tituloEleitorSecao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tituloEleitorUf {
            get {
                return this.tituloEleitorUfField;
            }
            set {
                if ((object.ReferenceEquals(this.tituloEleitorUfField, value) != true)) {
                    this.tituloEleitorUfField = value;
                    this.RaisePropertyChanged("tituloEleitorUf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tituloEleitorZona {
            get {
                return this.tituloEleitorZonaField;
            }
            set {
                if ((object.ReferenceEquals(this.tituloEleitorZonaField, value) != true)) {
                    this.tituloEleitorZonaField = value;
                    this.RaisePropertyChanged("tituloEleitorZona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoTitulacao", Namespace="http://schemas.datacontract.org/2004/07/ufmt.sig.entity")]
    [System.SerializableAttribute()]
    public partial class TipoTitulacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string descricaoField;
        
        private int tipoTitulacaoUIDField;
        
        private System.Nullable<int> titulacaoSiapeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int tipoTitulacaoUID {
            get {
                return this.tipoTitulacaoUIDField;
            }
            set {
                if ((this.tipoTitulacaoUIDField.Equals(value) != true)) {
                    this.tipoTitulacaoUIDField = value;
                    this.RaisePropertyChanged("tipoTitulacaoUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> titulacaoSiape {
            get {
                return this.titulacaoSiapeField;
            }
            set {
                if ((this.titulacaoSiapeField.Equals(value) != true)) {
                    this.titulacaoSiapeField = value;
                    this.RaisePropertyChanged("titulacaoSiape");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PessoaEntity", Namespace="http://schemas.datacontract.org/2004/07/ufmt.services.entities")]
    [System.SerializableAttribute()]
    public partial class PessoaEntity : ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.Pessoa {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagemPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkLattesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NivelPadraoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ServidorUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiapeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.Tipo TipoPessoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.UnidadeEntity UnidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.SituacaoDoServidor situacaoDoServidorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImagemPerfil {
            get {
                return this.ImagemPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagemPerfilField, value) != true)) {
                    this.ImagemPerfilField = value;
                    this.RaisePropertyChanged("ImagemPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkLattes {
            get {
                return this.LinkLattesField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkLattesField, value) != true)) {
                    this.LinkLattesField = value;
                    this.RaisePropertyChanged("LinkLattes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NivelPadrao {
            get {
                return this.NivelPadraoField;
            }
            set {
                if ((object.ReferenceEquals(this.NivelPadraoField, value) != true)) {
                    this.NivelPadraoField = value;
                    this.RaisePropertyChanged("NivelPadrao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ServidorUID {
            get {
                return this.ServidorUIDField;
            }
            set {
                if ((this.ServidorUIDField.Equals(value) != true)) {
                    this.ServidorUIDField = value;
                    this.RaisePropertyChanged("ServidorUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Siape {
            get {
                return this.SiapeField;
            }
            set {
                if ((object.ReferenceEquals(this.SiapeField, value) != true)) {
                    this.SiapeField = value;
                    this.RaisePropertyChanged("Siape");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.Tipo TipoPessoa {
            get {
                return this.TipoPessoaField;
            }
            set {
                if ((this.TipoPessoaField.Equals(value) != true)) {
                    this.TipoPessoaField = value;
                    this.RaisePropertyChanged("TipoPessoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.UnidadeEntity Unidade {
            get {
                return this.UnidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadeField, value) != true)) {
                    this.UnidadeField = value;
                    this.RaisePropertyChanged("Unidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.SituacaoDoServidor situacaoDoServidor {
            get {
                return this.situacaoDoServidorField;
            }
            set {
                if ((this.situacaoDoServidorField.Equals(value) != true)) {
                    this.situacaoDoServidorField = value;
                    this.RaisePropertyChanged("situacaoDoServidor");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tipo", Namespace="http://schemas.datacontract.org/2004/07/ufmt.services.entities")]
    public enum Tipo : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Servidor = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlunoGraduacao = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlunoPos = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SituacaoDoServidor", Namespace="http://schemas.datacontract.org/2004/07/ufmt.services")]
    public enum SituacaoDoServidor : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ativo = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Afastado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cedido = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inativo = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Excluido = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EspacoFisicoEntity", Namespace="http://schemas.datacontract.org/2004/07/ufmt.services.entities")]
    [System.SerializableAttribute()]
    public partial class EspacoFisicoEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AndarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlocoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeUnidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PredioNomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegiaoNomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEspacoFisicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoSalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadeNomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long unidadeUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Andar {
            get {
                return this.AndarField;
            }
            set {
                if ((object.ReferenceEquals(this.AndarField, value) != true)) {
                    this.AndarField = value;
                    this.RaisePropertyChanged("Andar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bloco {
            get {
                return this.BlocoField;
            }
            set {
                if ((object.ReferenceEquals(this.BlocoField, value) != true)) {
                    this.BlocoField = value;
                    this.RaisePropertyChanged("Bloco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUnidade {
            get {
                return this.NomeUnidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeUnidadeField, value) != true)) {
                    this.NomeUnidadeField = value;
                    this.RaisePropertyChanged("NomeUnidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PredioNome {
            get {
                return this.PredioNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.PredioNomeField, value) != true)) {
                    this.PredioNomeField = value;
                    this.RaisePropertyChanged("PredioNome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegiaoNome {
            get {
                return this.RegiaoNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.RegiaoNomeField, value) != true)) {
                    this.RegiaoNomeField = value;
                    this.RaisePropertyChanged("RegiaoNome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sala {
            get {
                return this.SalaField;
            }
            set {
                if ((this.SalaField.Equals(value) != true)) {
                    this.SalaField = value;
                    this.RaisePropertyChanged("Sala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoEspacoFisico {
            get {
                return this.TipoEspacoFisicoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEspacoFisicoField, value) != true)) {
                    this.TipoEspacoFisicoField = value;
                    this.RaisePropertyChanged("TipoEspacoFisico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoSala {
            get {
                return this.TipoSalaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoSalaField, value) != true)) {
                    this.TipoSalaField = value;
                    this.RaisePropertyChanged("TipoSala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadeNome {
            get {
                return this.UnidadeNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadeNomeField, value) != true)) {
                    this.UnidadeNomeField = value;
                    this.RaisePropertyChanged("UnidadeNome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long unidadeUID {
            get {
                return this.unidadeUIDField;
            }
            set {
                if ((this.unidadeUIDField.Equals(value) != true)) {
                    this.unidadeUIDField = value;
                    this.RaisePropertyChanged("unidadeUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocalizacaoReference.ILocalizacao")]
    public interface ILocalizacao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacao/GetUnidades", ReplyAction="http://tempuri.org/ILocalizacao/GetUnidadesResponse")]
        ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.UnidadeEntity[] GetUnidades(string nomeParcial, System.Nullable<int> campusUID, System.Nullable<bool> apenasAtivos, System.Nullable<int> registroInicial, System.Nullable<int> quantidadeRegistros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacao/GetUnidades", ReplyAction="http://tempuri.org/ILocalizacao/GetUnidadesResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.UnidadeEntity[]> GetUnidadesAsync(string nomeParcial, System.Nullable<int> campusUID, System.Nullable<bool> apenasAtivos, System.Nullable<int> registroInicial, System.Nullable<int> quantidadeRegistros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacao/GetUnidade", ReplyAction="http://tempuri.org/ILocalizacao/GetUnidadeResponse")]
        ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.UnidadeEntity GetUnidade(long unidadeUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacao/GetUnidade", ReplyAction="http://tempuri.org/ILocalizacao/GetUnidadeResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.UnidadeEntity> GetUnidadeAsync(long unidadeUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacao/GetCampi", ReplyAction="http://tempuri.org/ILocalizacao/GetCampiResponse")]
        ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.CampusEntity[] GetCampi(string nomeParcial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacao/GetCampi", ReplyAction="http://tempuri.org/ILocalizacao/GetCampiResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.CampusEntity[]> GetCampiAsync(string nomeParcial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacao/GetUnidadePorResponsavel", ReplyAction="http://tempuri.org/ILocalizacao/GetUnidadePorResponsavelResponse")]
        ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.UnidadeEntity GetUnidadePorResponsavel(long pessoaUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacao/GetUnidadePorResponsavel", ReplyAction="http://tempuri.org/ILocalizacao/GetUnidadePorResponsavelResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.UnidadeEntity> GetUnidadePorResponsavelAsync(long pessoaUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacao/GetUnidadesPorUnidadeSuperior", ReplyAction="http://tempuri.org/ILocalizacao/GetUnidadesPorUnidadeSuperiorResponse")]
        ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.UnidadeEntity[] GetUnidadesPorUnidadeSuperior(long unidadeUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacao/GetUnidadesPorUnidadeSuperior", ReplyAction="http://tempuri.org/ILocalizacao/GetUnidadesPorUnidadeSuperiorResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.UnidadeEntity[]> GetUnidadesPorUnidadeSuperiorAsync(long unidadeUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacao/GetNomeCampiPorUnidade", ReplyAction="http://tempuri.org/ILocalizacao/GetNomeCampiPorUnidadeResponse")]
        string GetNomeCampiPorUnidade(long unidadeUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacao/GetNomeCampiPorUnidade", ReplyAction="http://tempuri.org/ILocalizacao/GetNomeCampiPorUnidadeResponse")]
        System.Threading.Tasks.Task<string> GetNomeCampiPorUnidadeAsync(long unidadeUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacao/GetCampiGeral", ReplyAction="http://tempuri.org/ILocalizacao/GetCampiGeralResponse")]
        ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.CampiEntity[] GetCampiGeral();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacao/GetCampiGeral", ReplyAction="http://tempuri.org/ILocalizacao/GetCampiGeralResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.CampiEntity[]> GetCampiGeralAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacao/GetPessoaResponsavelPorUnidade", ReplyAction="http://tempuri.org/ILocalizacao/GetPessoaResponsavelPorUnidadeResponse")]
        ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.PessoaEntity GetPessoaResponsavelPorUnidade(long unidadeUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacao/GetPessoaResponsavelPorUnidade", ReplyAction="http://tempuri.org/ILocalizacao/GetPessoaResponsavelPorUnidadeResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.PessoaEntity> GetPessoaResponsavelPorUnidadeAsync(long unidadeUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacao/GetEspacoFisicoPorUnidade", ReplyAction="http://tempuri.org/ILocalizacao/GetEspacoFisicoPorUnidadeResponse")]
        ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.EspacoFisicoEntity[] GetEspacoFisicoPorUnidade(long unidadeUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacao/GetEspacoFisicoPorUnidade", ReplyAction="http://tempuri.org/ILocalizacao/GetEspacoFisicoPorUnidadeResponse")]
        System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.EspacoFisicoEntity[]> GetEspacoFisicoPorUnidadeAsync(long unidadeUID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILocalizacaoChannel : ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.ILocalizacao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocalizacaoClient : System.ServiceModel.ClientBase<ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.ILocalizacao>, ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.ILocalizacao {
        
        public LocalizacaoClient() {
        }
        
        public LocalizacaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocalizacaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalizacaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalizacaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.UnidadeEntity[] GetUnidades(string nomeParcial, System.Nullable<int> campusUID, System.Nullable<bool> apenasAtivos, System.Nullable<int> registroInicial, System.Nullable<int> quantidadeRegistros) {
            return base.Channel.GetUnidades(nomeParcial, campusUID, apenasAtivos, registroInicial, quantidadeRegistros);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.UnidadeEntity[]> GetUnidadesAsync(string nomeParcial, System.Nullable<int> campusUID, System.Nullable<bool> apenasAtivos, System.Nullable<int> registroInicial, System.Nullable<int> quantidadeRegistros) {
            return base.Channel.GetUnidadesAsync(nomeParcial, campusUID, apenasAtivos, registroInicial, quantidadeRegistros);
        }
        
        public ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.UnidadeEntity GetUnidade(long unidadeUID) {
            return base.Channel.GetUnidade(unidadeUID);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.UnidadeEntity> GetUnidadeAsync(long unidadeUID) {
            return base.Channel.GetUnidadeAsync(unidadeUID);
        }
        
        public ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.CampusEntity[] GetCampi(string nomeParcial) {
            return base.Channel.GetCampi(nomeParcial);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.CampusEntity[]> GetCampiAsync(string nomeParcial) {
            return base.Channel.GetCampiAsync(nomeParcial);
        }
        
        public ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.UnidadeEntity GetUnidadePorResponsavel(long pessoaUID) {
            return base.Channel.GetUnidadePorResponsavel(pessoaUID);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.UnidadeEntity> GetUnidadePorResponsavelAsync(long pessoaUID) {
            return base.Channel.GetUnidadePorResponsavelAsync(pessoaUID);
        }
        
        public ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.UnidadeEntity[] GetUnidadesPorUnidadeSuperior(long unidadeUID) {
            return base.Channel.GetUnidadesPorUnidadeSuperior(unidadeUID);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.UnidadeEntity[]> GetUnidadesPorUnidadeSuperiorAsync(long unidadeUID) {
            return base.Channel.GetUnidadesPorUnidadeSuperiorAsync(unidadeUID);
        }
        
        public string GetNomeCampiPorUnidade(long unidadeUID) {
            return base.Channel.GetNomeCampiPorUnidade(unidadeUID);
        }
        
        public System.Threading.Tasks.Task<string> GetNomeCampiPorUnidadeAsync(long unidadeUID) {
            return base.Channel.GetNomeCampiPorUnidadeAsync(unidadeUID);
        }
        
        public ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.CampiEntity[] GetCampiGeral() {
            return base.Channel.GetCampiGeral();
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.CampiEntity[]> GetCampiGeralAsync() {
            return base.Channel.GetCampiGeralAsync();
        }
        
        public ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.PessoaEntity GetPessoaResponsavelPorUnidade(long unidadeUID) {
            return base.Channel.GetPessoaResponsavelPorUnidade(unidadeUID);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.PessoaEntity> GetPessoaResponsavelPorUnidadeAsync(long unidadeUID) {
            return base.Channel.GetPessoaResponsavelPorUnidadeAsync(unidadeUID);
        }
        
        public ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.EspacoFisicoEntity[] GetEspacoFisicoPorUnidade(long unidadeUID) {
            return base.Channel.GetEspacoFisicoPorUnidade(unidadeUID);
        }
        
        public System.Threading.Tasks.Task<ufmt.br.bolsa.auxilio.siafi.LocalizacaoReference.EspacoFisicoEntity[]> GetEspacoFisicoPorUnidadeAsync(long unidadeUID) {
            return base.Channel.GetEspacoFisicoPorUnidadeAsync(unidadeUID);
        }
    }
}
