//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema.avdf.varzeagrande.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspectosocial
    {
        public int aspectoSocialUID { get; set; }
        public Nullable<int> pessoaID { get; set; }
        public Nullable<bool> carteiraPasseLivre { get; set; }
        public string descCarteiraPasseLivre { get; set; }
        public Nullable<bool> utilizaProjeto { get; set; }
        public string descUtilizaProjeto { get; set; }
        public Nullable<bool> bpcLoas { get; set; }
        public Nullable<bool> recebeAposentadoria { get; set; }
        public Nullable<int> situacaoMoradia { get; set; }
        public Nullable<decimal> rendaFamiliar { get; set; }
        public Nullable<bool> trabalhando { get; set; }
        public string descTrabalhando { get; set; }
        public Nullable<int> grauEscolaridade { get; set; }
        public Nullable<int> AspectoSocial1 { get; set; }
        public string descProfissao { get; set; }
        public Nullable<int> estadoCivil { get; set; }
        public Nullable<bool> temFilhos { get; set; }
        public Nullable<int> qtdeFilhos { get; set; }
        public string nomeConjuge { get; set; }
        public string sexoConjuge { get; set; }
        public Nullable<System.DateTime> dataNascimentoConjuge { get; set; }
        public Nullable<int> naturalidadeEstadoConjuge { get; set; }
        public Nullable<int> naturalidadeCidadeConjuge { get; set; }
        public string rgConjuge { get; set; }
        public string cpfConjuge { get; set; }
        public string nte { get; set; }
        public string sessaoEleitoral { get; set; }
        public string zonaEleitoral { get; set; }
        public string nomeMaeConjuge { get; set; }
        public string nomePaiConjuge { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
    
        public virtual pessoa pessoa { get; set; }
    }
}
