//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema.avdf.varzeagrande.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class idbavdfvgEntities : DbContext
    {
        public idbavdfvgEntities()
            : base("name=idbavdfvgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aspectosocial> aspectosocial { get; set; }
        public virtual DbSet<patologia> patologia { get; set; }
        public virtual DbSet<pessoa> pessoa { get; set; }
        public virtual DbSet<tb_cidades> tb_cidades { get; set; }
        public virtual DbSet<tb_estados> tb_estados { get; set; }
    }
}
