//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema.avdf.varzeagrande.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patologia
    {
        public int patologiaUID { get; set; }
        public Nullable<int> pessoaUID { get; set; }
        public Nullable<bool> patologia1 { get; set; }
        public string causaPatologia { get; set; }
        public string deficienciaApresentada { get; set; }
        public Nullable<int> tipoDeficiencia { get; set; }
        public Nullable<int> acessibilidadeMobilidade { get; set; }
        public Nullable<bool> deficienciaColuna { get; set; }
        public Nullable<bool> usaAparelho { get; set; }
        public string descTipoAparelho { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
    
        public virtual pessoa pessoa { get; set; }
    }
}
