//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema.avdf.varzeagrande.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pessoa()
        {
            this.aspectosocial = new HashSet<aspectosocial>();
            this.patologia = new HashSet<patologia>();
        }
    
        public int pessoaUID { get; set; }
        public string nome { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
        public long estadoUID { get; set; }
        public long cidadeUID { get; set; }
        public string rg { get; set; }
        public string cpf { get; set; }
        public string nomeMae { get; set; }
        public string nomePai { get; set; }
        public string cep { get; set; }
        public string rua { get; set; }
        public string casa { get; set; }
        public string bairro { get; set; }
        public string quadra { get; set; }
        public string complemento { get; set; }
        public string telefone1 { get; set; }
        public string telefone2 { get; set; }
        public string telefone3 { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
        public Nullable<int> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspectosocial> aspectosocial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patologia> patologia { get; set; }
        public virtual tb_cidades tb_cidades { get; set; }
        public virtual tb_estados tb_estados { get; set; }
    }
}
